version: '3'
services:
  web:
    build:
      context: .
      target: development
    ports:
      - 8000:8000
    volumes:
      - .:/app
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=meter
      - POSTGRES_PASSWORD=meter
      - POSTGRES_DB=meter  
  adminer:
    image: adminer:4
    ports:
      - 127.0.0.1:8080:8080
