from meter.constant import ExtendedEnum


class RulePosition(ExtendedEnum):
    # Reservoir
    SHIMEN_RESERVOIR = "SHIMEN_RESERVOIR"
    FEITSUI_RESERVOIR = "FEITSUI_RESERVOIR"
    SECOND_BAOSHAN_RESERVOIR = "SECOND_BAOSHAN_RESERVOIR"
    YONGHESHAN_RESERVOIR = "YONGHESHAN_RESERVOIR"
    MINGDE_RESERVOIR = "MINGDE_RESERVOIR"
    LIYUTAN_RESERVOIR = "LIYUTAN_RESERVOIR"
    DEJI_RESERVOIR = "DEJI_RESERVOIR"
    SHIGANG_DAM = "SHIGANG_DAM"
    WUSHE_RESERVOIR = "WUSHE_RESERVOIR"
    SUN_MOON_LAKE_RESERVOIR = "SUN_MOON_LAKE_RESERVOIR"
    JIJI_WEIR = "JIJI_WEIR"
    HUSHAN_RESERVOIR = "HUSHAN_RESERVOIR"
    RENYITAN_RESERVOIR = "RENYITAN_RESERVOIR"
    BAIHE_RESERVOIR = "BAIHE_RESERVOIR"
    WUSHANTOU_RESERVOIR = "WUSHANTOU_RESERVOIR"
    ZENGWEN_RESERVOIR = "ZENGWEN_RESERVOIR"
    NANHUA_RESERVOIR = "NANHUA_RESERVOIR"
    AGONGDIAN_RESERVOIR = "AGONGDIAN_RESERVOIR"
    GAOPING_RIVER_WEIR = "GAOPING_RIVER_WEIR"
    MUDAN_RESERVOIR = "MUDAN_RESERVOIR"

    # Electricity
    ELECTRICITY_SUFFIX = "_ELECTRICITY"
    EAST_ELECTRICITY = "EAST" + ELECTRICITY_SUFFIX
    SOUTH_ELECTRICITY = "SOUTH" + ELECTRICITY_SUFFIX
    CENTRAL_ELECTRICITY = "CENTRAL" + ELECTRICITY_SUFFIX
    NORTH_ELECTRICITY = "NORTH" + ELECTRICITY_SUFFIX

    # Earthquake
    HSINCHU_EARTHQUAKE = "HSINCHU_EARTHQUAKE"
    TAICHUNG_EARTHQUAKE = "TAICHUNG_EARTHQUAKE"
    TAINAN_EARTHQUAKE = "TAINAN_EARTHQUAKE"
